import { Employee } from '../types';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    employeeRef: 'EMP/2026/0001',
    firstName: 'Aarav',
    lastName: 'Mehta',
    fullName: 'Aarav Mehta',
    initials: 'AM',
    gender: 'male',
    dateOfBirth: '1992-04-15',
    maritalStatus: 'married',
    nationality: 'Indian',
    jobPosition: 'Senior Software Engineer',
    jobTitle: 'Backend Lead',
    department: 'Engineering',
    workEmail: 'aarav.mehta@peoplepay360.com',
    workPhone: '+91 98765 43210',
    personalEmail: 'aarav.mehta@gmail.com',
    hireDate: '2022-03-01',
    status: 'active',
    managerName: 'Priya Kapoor',
    managerId: 'emp-005',
    workLocation: 'Bengaluru HQ',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Regular Salary',
    tags: ['backend', 'python', 'lead'],
    createdAt: '2022-03-01T08:00:00Z',
    updatedAt: '2026-08-15T10:30:00Z',
  },
  {
    id: 'emp-002',
    employeeRef: 'EMP/2026/0002',
    firstName: 'Priya',
    lastName: 'Sharma',
    fullName: 'Priya Sharma',
    initials: 'PS',
    gender: 'female',
    dateOfBirth: '1990-07-22',
    maritalStatus: 'single',
    nationality: 'Indian',
    jobPosition: 'HR Business Partner',
    jobTitle: 'Senior HR Manager',
    department: 'Human Resources',
    workEmail: 'priya.sharma@peoplepay360.com',
    workPhone: '+91 98765 11111',
    hireDate: '2021-06-15',
    status: 'active',
    managerName: 'Rohit Verma',
    managerId: 'emp-006',
    workLocation: 'Mumbai Office',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Regular Salary',
    tags: ['hr', 'recruitment', 'payroll'],
    createdAt: '2021-06-15T08:00:00Z',
    updatedAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'emp-003',
    employeeRef: 'EMP/2026/0003',
    firstName: 'Rohan',
    lastName: 'Gupta',
    fullName: 'Rohan Gupta',
    initials: 'RG',
    gender: 'male',
    dateOfBirth: '1995-11-10',
    maritalStatus: 'single',
    nationality: 'Indian',
    jobPosition: 'Product Manager',
    jobTitle: 'PM - Growth',
    department: 'Product',
    workEmail: 'rohan.gupta@peoplepay360.com',
    workPhone: '+91 98765 22222',
    hireDate: '2023-01-10',
    status: 'active',
    managerName: 'Priya Kapoor',
    managerId: 'emp-005',
    workLocation: 'Bengaluru HQ',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Regular Salary',
    tags: ['product', 'growth', 'agile'],
    createdAt: '2023-01-10T08:00:00Z',
    updatedAt: '2026-07-20T14:00:00Z',
  },
  {
    id: 'emp-004',
    employeeRef: 'EMP/2026/0004',
    firstName: 'Ananya',
    lastName: 'Patel',
    fullName: 'Ananya Patel',
    initials: 'AP',
    gender: 'female',
    dateOfBirth: '1997-03-05',
    maritalStatus: 'single',
    nationality: 'Indian',
    jobPosition: 'UX Designer',
    jobTitle: 'Senior UX/UI Designer',
    department: 'Design',
    workEmail: 'ananya.patel@peoplepay360.com',
    workPhone: '+91 98765 33333',
    hireDate: '2024-02-20',
    status: 'probation',
    managerName: 'Rohan Gupta',
    managerId: 'emp-003',
    workLocation: 'Remote',
    workScheduleName: 'Flexible 35h',
    salaryStructureName: 'Regular Salary',
    tags: ['design', 'figma', 'ux'],
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2026-08-28T16:00:00Z',
  },
  {
    id: 'emp-005',
    employeeRef: 'EMP/2026/0005',
    firstName: 'Priya',
    lastName: 'Kapoor',
    fullName: 'Priya Kapoor',
    initials: 'PK',
    gender: 'female',
    dateOfBirth: '1985-09-18',
    maritalStatus: 'married',
    nationality: 'Indian',
    jobPosition: 'Vice President - Engineering',
    jobTitle: 'VP Engineering',
    department: 'Engineering',
    workEmail: 'priya.kapoor@peoplepay360.com',
    workPhone: '+91 98765 44444',
    hireDate: '2019-07-01',
    status: 'active',
    workLocation: 'Bengaluru HQ',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Executive Salary',
    tags: ['engineering', 'leadership', 'strategy'],
    createdAt: '2019-07-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'emp-006',
    employeeRef: 'EMP/2026/0006',
    firstName: 'Rohit',
    lastName: 'Verma',
    fullName: 'Rohit Verma',
    initials: 'RV',
    gender: 'male',
    dateOfBirth: '1982-12-30',
    maritalStatus: 'married',
    nationality: 'Indian',
    jobPosition: 'Chief Human Resources Officer',
    jobTitle: 'CHRO',
    department: 'Human Resources',
    workEmail: 'rohit.verma@peoplepay360.com',
    workPhone: '+91 98765 55555',
    hireDate: '2018-01-15',
    status: 'active',
    workLocation: 'Mumbai Office',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Executive Salary',
    tags: ['hr', 'leadership', 'compliance'],
    createdAt: '2018-01-15T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'emp-007',
    employeeRef: 'EMP/2026/0007',
    firstName: 'Kavya',
    lastName: 'Nair',
    fullName: 'Kavya Nair',
    initials: 'KN',
    gender: 'female',
    dateOfBirth: '1993-06-25',
    maritalStatus: 'single',
    nationality: 'Indian',
    jobPosition: 'Payroll Specialist',
    jobTitle: 'Senior Payroll Analyst',
    department: 'Finance',
    workEmail: 'kavya.nair@peoplepay360.com',
    workPhone: '+91 98765 66666',
    hireDate: '2022-08-01',
    status: 'active',
    managerName: 'Rohit Verma',
    managerId: 'emp-006',
    workLocation: 'Mumbai Office',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Regular Salary',
    tags: ['finance', 'payroll', 'compliance'],
    createdAt: '2022-08-01T08:00:00Z',
    updatedAt: '2026-08-10T11:00:00Z',
  },
  {
    id: 'emp-008',
    employeeRef: 'EMP/2026/0008',
    firstName: 'Arjun',
    lastName: 'Singh',
    fullName: 'Arjun Singh',
    initials: 'AS',
    gender: 'male',
    dateOfBirth: '1998-01-14',
    maritalStatus: 'single',
    nationality: 'Indian',
    jobPosition: 'Frontend Developer',
    jobTitle: 'Junior Frontend Engineer',
    department: 'Engineering',
    workEmail: 'arjun.singh@peoplepay360.com',
    workPhone: '+91 98765 77777',
    hireDate: '2025-03-01',
    status: 'probation',
    managerName: 'Aarav Mehta',
    managerId: 'emp-001',
    workLocation: 'Bengaluru HQ',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Regular Salary',
    tags: ['frontend', 'react', 'typescript'],
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'emp-009',
    employeeRef: 'EMP/2026/0009',
    firstName: 'Meera',
    lastName: 'Reddy',
    fullName: 'Meera Reddy',
    initials: 'MR',
    gender: 'female',
    dateOfBirth: '1991-08-19',
    maritalStatus: 'married',
    nationality: 'Indian',
    jobPosition: 'Finance Manager',
    jobTitle: 'Head of Finance',
    department: 'Finance',
    workEmail: 'meera.reddy@peoplepay360.com',
    workPhone: '+91 98765 88888',
    hireDate: '2020-04-15',
    status: 'active',
    workLocation: 'Hyderabad Office',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Regular Salary',
    tags: ['finance', 'accounting', 'reporting'],
    createdAt: '2020-04-15T08:00:00Z',
    updatedAt: '2026-08-25T12:00:00Z',
  },
  {
    id: 'emp-010',
    employeeRef: 'EMP/2026/0010',
    firstName: 'Vikram',
    lastName: 'Bose',
    fullName: 'Vikram Bose',
    initials: 'VB',
    gender: 'male',
    dateOfBirth: '1989-05-30',
    maritalStatus: 'divorced',
    nationality: 'Indian',
    jobPosition: 'Sales Director',
    jobTitle: 'Director of Sales',
    department: 'Sales',
    workEmail: 'vikram.bose@peoplepay360.com',
    workPhone: '+91 98765 99999',
    hireDate: '2021-09-01',
    status: 'on_leave',
    workLocation: 'Delhi NCR',
    workScheduleName: '40h Standard Week',
    salaryStructureName: 'Sales Salary',
    tags: ['sales', 'leadership', 'b2b'],
    createdAt: '2021-09-01T08:00:00Z',
    updatedAt: '2026-09-03T10:00:00Z',
  },
];

export const getEmployeeById = (id: string): Employee | undefined =>
  MOCK_EMPLOYEES.find((e) => e.id === id);
