import type { WorkingSchedule } from '../types';

export const MOCK_SCHEDULES: WorkingSchedule[] = [
  {
    id: 'sch-001',
    name: 'Standard 40h/week',
    type: 'fixed',
    hoursPerWeek: 40,
    timezone: 'Asia/Kolkata',
    status: 'active',
    days: [
      { day: 'monday',    isWorkDay: true,  dayPeriod: 'full', startTime: '09:00', endTime: '18:00', hours: 9 },
      { day: 'tuesday',   isWorkDay: true,  dayPeriod: 'full', startTime: '09:00', endTime: '18:00', hours: 9 },
      { day: 'wednesday', isWorkDay: true,  dayPeriod: 'full', startTime: '09:00', endTime: '18:00', hours: 9 },
      { day: 'thursday',  isWorkDay: true,  dayPeriod: 'full', startTime: '09:00', endTime: '18:00', hours: 9 },
      { day: 'friday',    isWorkDay: true,  dayPeriod: 'full', startTime: '09:00', endTime: '17:00', hours: 8 },
      { day: 'saturday',  isWorkDay: false },
      { day: 'sunday',    isWorkDay: false },
    ],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sch-002',
    name: 'Flexible Hours',
    type: 'flexible',
    hoursPerWeek: 35,
    timezone: 'Asia/Kolkata',
    status: 'active',
    days: [
      { day: 'monday',    isWorkDay: true,  dayPeriod: 'full', startTime: '10:00', endTime: '18:00', hours: 7 },
      { day: 'tuesday',   isWorkDay: true,  dayPeriod: 'full', startTime: '10:00', endTime: '18:00', hours: 7 },
      { day: 'wednesday', isWorkDay: true,  dayPeriod: 'full', startTime: '10:00', endTime: '18:00', hours: 7 },
      { day: 'thursday',  isWorkDay: true,  dayPeriod: 'full', startTime: '10:00', endTime: '18:00', hours: 7 },
      { day: 'friday',    isWorkDay: true,  dayPeriod: 'full', startTime: '10:00', endTime: '17:00', hours: 7 },
      { day: 'saturday',  isWorkDay: false },
      { day: 'sunday',    isWorkDay: false },
    ],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sch-003',
    name: 'Part-time (20h/week)',
    type: 'fixed',
    hoursPerWeek: 20,
    timezone: 'Asia/Kolkata',
    status: 'active',
    days: [
      { day: 'monday',    isWorkDay: true,  dayPeriod: 'morning', startTime: '09:00', endTime: '13:00', hours: 4 },
      { day: 'tuesday',   isWorkDay: true,  dayPeriod: 'morning', startTime: '09:00', endTime: '13:00', hours: 4 },
      { day: 'wednesday', isWorkDay: true,  dayPeriod: 'morning', startTime: '09:00', endTime: '13:00', hours: 4 },
      { day: 'thursday',  isWorkDay: true,  dayPeriod: 'morning', startTime: '09:00', endTime: '13:00', hours: 4 },
      { day: 'friday',    isWorkDay: true,  dayPeriod: 'morning', startTime: '09:00', endTime: '13:00', hours: 4 },
      { day: 'saturday',  isWorkDay: false },
      { day: 'sunday',    isWorkDay: false },
    ],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sch-004',
    name: 'Night Shift',
    type: 'shift',
    hoursPerWeek: 40,
    timezone: 'Asia/Kolkata',
    status: 'active',
    days: [
      { day: 'monday',    isWorkDay: true,  dayPeriod: 'full', startTime: '21:00', endTime: '06:00', hours: 9 },
      { day: 'tuesday',   isWorkDay: true,  dayPeriod: 'full', startTime: '21:00', endTime: '06:00', hours: 9 },
      { day: 'wednesday', isWorkDay: true,  dayPeriod: 'full', startTime: '21:00', endTime: '06:00', hours: 9 },
      { day: 'thursday',  isWorkDay: true,  dayPeriod: 'full', startTime: '21:00', endTime: '06:00', hours: 9 },
      { day: 'friday',    isWorkDay: true,  dayPeriod: 'full', startTime: '21:00', endTime: '06:00', hours: 8 },
      { day: 'saturday',  isWorkDay: false },
      { day: 'sunday',    isWorkDay: false },
    ],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];
